name    'KyleAnderson-uci'
version '0.0.3'
source 'https://github.com/solarkennedy/puppet-uci'
author 'Kyle Anderson'
license 'Apache License, Version 2.0'
summary 'Module for defining OpenWrt UCI settings'
description 'Module for defining OpenWrt UCI settings'
project_page 'https://github.com/solarkennedy/puppet-uci'
